@startuml

Actor Admin
participant TeacherManagementController
participant TeacherService
participant TeacherRepository
participant IGenericMapper
participant AccountService
database MySQL

autonumber 1.0
Admin -> TeacherManagementController: get teacher by id
activate Admin
activate TeacherManagementController
TeacherManagementController -> TeacherService: get teacher dto by id

activate TeacherService
TeacherService -> TeacherRepository: find by id

activate TeacherRepository
TeacherRepository -> MySQL: select

activate MySQL
MySQL --> TeacherRepository: return response
deactivate MySQL

TeacherRepository --> TeacherService: return teacher
deactivate TeacherRepository

autonumber 2.0
TeacherService -> IGenericMapper: map to teacher dto

activate IGenericMapper
IGenericMapper -> AccountService: get account dto by id
activate AccountService
AccountService --> IGenericMapper: return account dto
deactivate AccountService
IGenericMapper --> TeacherService: return teacher dto
deactivate IGenericMapper

TeacherService --> TeacherManagementController: return teacher dto
deactivate TeacherService
TeacherManagementController --> Admin: return teacher dto
deactivate TeacherManagementController
deactivate Admin


@enduml